name: Koncur Kantra

inputs:
  skip_maven:
    description: "Whether to setup access to the testing maven packages"
    default: true
    type: boolean
  os:
    description: OS that the action is running on, one of macos, windows, linux
    required: true
    type: string
  image_pattern:
    description: The pattern used to download the image's that have been built to test
    required: false
    type: string
  ref:
    description: The ref of koncur to use for testing
    required: false
    type: string
    default: main

runs:
  using: "composite"
  steps:
    ## Podman Setup
    - name: Install podman (macos)
      if: ${{ inputs.os == 'macos' }}
      shell: bash
      run: |
        brew install podman
        podman machine init --rootful --memory 8192 --cpus 2
        podman machine start 
        echo "NETWORK_GATEWAY=host.containers.internal" >> $GITHUB_ENV

    - name: Install podman (windows)
      if: ${{ inputs.os == 'windows' }}
      shell: bash
      run: |
        choco install podman-cli
        podman machine init --rootful --memory 10240 --cpus 3
        podman machine start 

    - name: Also add local/bin to windows path and get host wsl ip 
      if: ${{ inputs.os == 'windows' }}
      shell: powershell
      run: |
        $HOST_IP=Get-NetIpAddress | where { $_.InterfaceAlias -Like '*WSL*' -and $_.AddressFamily -EQ "IPv4" } | select -ExpandProperty IPAddress
        $HOST_IP
        Write-Output "NETWORK_GATEWAY=$HOST_IP" >> $env:GITHUB_ENV
        $newPath = "$HOME\.local\bin"
        Write-Output "$newPath" >> $env:GITHUB_PATH

    - name: Create containers config for host networking
      if: ${{ inputs.os == 'linux' }}
      shell: bash
      run: |
        mkdir -p $HOME/.config/containers
        cat <<-EOF > /$HOME/.config/containers//containers.conf
        # [containers]
        # netns="host"
        [network]
        network_cmd_options = ["allow_host_loopback=true"]
        EOF


    - name: Verify local/bin is on the path
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo $HOME/.local/bin >> $GITHUB_PATH
      
      ## Loading images
    
    - name: Download Images from artifacts
      id: download-artifacts
      continue-on-error: true 
      if: ${{ inputs.image_pattern }}
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.image_pattern }}
        path: ${{ runner.temp }}/images
        merge-multiple: true

    - name: Load images into podman
      if: ${{ inputs.image_pattern }}
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/load_img.sh ${RUNNER_TEMP}/images
        rm -rf ${RUNNER_TEMP}/images

    ## Run this check only when the downloading was not skipped.
    - name: Check and download missing images
      if: ${{ steps.download-artifacts.outcome == 'failure' || steps.download-artifacts.outcome == 'success' }}
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/check_images.sh

    ## Koncur testing
    - name: Download and install kantra (macos)
      if: ${{ inputs.os == 'macos' }}
      shell: bash
      run: |
        podman cp $(podman create --name kantra-download $RUNNER_IMG):/usr/local/bin/darwin-kantra . &&\
        podman rm kantra-download
        cp darwin-kantra $HOME/.local/bin/kantra

    - name: Download and install kantra (windows)
      if: ${{ inputs.os == 'windows' }}
      shell: bash
      run: |
        podman cp $(podman create --name kantra-download $RUNNER_IMG):/usr/local/bin/windows-kantra . &&\
        podman rm kantra-download
        cp windows-kantra $HOME/.local/bin/kantra.exe
        ls -la $HOME/.local/bin/kantra.exe
        $HOME/.local/bin/kantra version

    - name: Download and install kantra (linux)
      if: ${{ inputs.os == 'linux' }}
      shell: bash
      run: |
        podman cp $(podman create --name kantra-download $RUNNER_IMG):/usr/local/bin/kantra . &&\
        podman rm kantra-download
        cp kantra $HOME/.local/bin/kantra
        podman network inspect podman
        echo "NETWORK_GATEWAY=host.containers.internal" >> $GITHUB_ENV

    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        repository: konveyor/koncur
        ref: ${{ inputs.ref }}

    - name: Setup go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build Koncur
      shell: bash
      run: |
        go build -o $HOME/.local/bin/koncur ./cmd/koncur/main.go

    - name: Allow firewall rule
      if: ${{ !inputs.skip_maven && inputs.os == 'windows-latest' }}
      shell: powershell
      run: |
        $wslAdapter = Get-NetAdapter | Where-Object {$_.Name -like "*WSL*"}
        if ($wslAdapter) {
          $wslIP = Get-NetIPAddress -InterfaceIndex $wslAdapter.InterfaceIndex | Where-Object {$_.AddressFamily -eq "IPv4"}
          if ($wslIP) {
            $networkRange = "$($wslIP.IPAddress)/$($wslIP.PrefixLength)"
            Write-Host "Found WSL network: $networkRange"
            netsh advfirewall firewall add rule name="WSL2-Auto" dir=in action=allow protocol=TCP remoteip=$networkRange
          }
        }

    - name: Run server for maven-local-resources
      if: ${{ !inputs.skip_maven }}
      uses: Eun/http-server-action@v1
      with:
        directory: local-maven-resources
        port: 8085

    - name: Set maven settings path (Windows)
      if: ${{ !inputs.skip_maven && inputs.os == 'windows' }}
      shell: bash
      run: |
        # Create directory using bash
        mkdir -p "$HOME/.koncur/temp"
        # Convert Unix path to Windows path for the env variable
        WINDOWS_PATH=$(cygpath -w "$HOME/.koncur/temp/settings.xml")
        echo "MAVEN_SETTINGS_PATH=$WINDOWS_PATH" >> $GITHUB_ENV

    - name: Set maven settings path (*nix)
      if: ${{ !inputs.skip_maven && inputs.os != 'windows-latest' }}
      shell: bash
      run: |
        mkdir -p "$HOME/.koncur/temp"
        echo "MAVEN_SETTINGS_PATH=$HOME/.koncur/temp/settings.xml" >> $GITHUB_ENV

    - name: Create maven settings file
      if: ${{ !inputs.skip_maven }}
      uses: s4u/maven-settings-action@v4.0.0
      with:
        githubServer: false
        repositories: '[{"id": "tackle-testapp-public", "name": "Local tackle-testapp repo", "url": "http://${{ env.NETWORK_GATEWAY }}:8085"}]'
        mirrors: '[{"id": "maven-default-http-blocker", "name": "disable http block", "mirrorOf": "tackle-testapp-public", "url": "http://${{ env.NETWORK_GATEWAY }}:8085", "blocked": false}]'
        path: "${{ env.MAVEN_SETTINGS_PATH }}"

    - name: Create kantra config
      if: ${{ !inputs.skip_maven }}
      shell: bash
      run: |
        mkdir -p .koncur/config
        cat << 'EOF' > .koncur/config/target-kantra.yaml
        type: kantra
        kantra:
          mavenSettings: '${{ env.MAVEN_SETTINGS_PATH }}'
        EOF

    - name: Run test
      shell: bash
      env:
        SKIP_MAVEN: ${{ fromJSON(inputs.skip_maven) }}
      run: |
        koncur run tests -t kantra -o yaml --output-file test.yaml


    - name: Upload output on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: koncur-kantra-${{ inputs.os }}-failures
        path: .koncur/output 
        retention-days: 5
        include-hidden-files: true

    - name: Upload result yaml
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: koncur-kantra-${{ inputs.os }}-summary
        path: test.yaml
        retention-days: 3
