name: Konveyor e2e nightly

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_call:
    inputs:
      branch:
        description: |
          The branch that should be used to pull all konveyor related repos.
          For example, if you wanted to set a nightly build for release-0.8, you would specify
          "release-0.8".
        required: false
        type: string
        default: main
  workflow_dispatch:
    inputs:
      branch:
        description: |
          The branch that should be used to pull all konveyor related repos.
          For example, if you wanted to set a nightly build for release-0.8, you would specify
          "release-0.8".
        required: false
        type: string
        default: main 

jobs:
  build-images: 
    runs-on: ubuntu-latest
    ## This should be a matrix that includes static-report 
    # rulesets which should trigger the hub and it's components BESIDES the addon-analyzer.
    # Java analyzer bundle triggers konveyor/analyzer-lsp (which includes all external providers in that repo).
    # Analyzer-LSP then needs to trigger kai, kantra, tackle-addon-analyzer.
    # Next we need to build the operator/operator-bundle using all the images.
    # Next we need to define the end-to-end tests to run and run a matrix for
    # 1. tackle2-hub/operator
    # 2. kantra -> Needs to run on mac/windows/linux
    # 3. kai -> Needs to run on mac/windows/linux
    # Each of these, needs to have a test for all the external providers built here
    # 1. java-external-provider
    # 2. javascript provider (needs rename)
    # 3. python provider
    # 4. golang provider
    strategy:
      matrix:
        config:
          - repo: "konveyor/tackle-keycloak-theme"
            image: "quay.io/konveyor/tackle-keycloak-init"
            dockerfile_path: "Dockerfile.init"
            context_path: "." 
          - repo: "konveyor/tackle2-ui"
            image: "quay.io/konveyor/tackle2-ui:latest"
            dockerfile_path: "Dockerfile"
            context_path: "."
          - repo: "konveyor/tackle2-addon-platform"
            image: "quay.io/konveyor/tackle2-addon-platform"
            dockerfile_path: "Dockerfile"
            context_path: "."
            go_mod_update:
              - "github.com/konveyor/tackle2-hub@${{ inputs.branch }}"
              - "github.com/konveyor/asset-generation@${{ inputs.branch }}"
              - "github.com/konveyor/tackle2-addon@${{ inputs.branch }}"
          - repo: "konveyor/kai"
            image: "quay.io/konveyor/kai-solution-server"
            dockerfile_path: ".kai_mcp_solution_server/tools/deploy/Containerfile"
            context_path: "./kai_mcp_solution_server"
          - repo: "konveyor/tackle2-addon-discovery"
            image: quay.io/konveyor/tackle2-addon-discovery
            dockerfile_path: "Dockerfile"
            context_path: "."
            go_mod_update:
              - "github.com/konveyor/tackle2-hub@${{ inputs.branch }}"
              - "github.com/konveyor/tackle2-addon@${{ inputs.branch }}"
          - repo: "konveyor/java-analyzer-bundle"
            image: "quay.io/konveyor/jdtls-server-base"
            dockerfile_path: "Dockerfile"
            context_path: "."
            dependent_jobs:
              - repo: "konveyor/analyzer-lsp"
                image: "quay.io/konveyor/analyzer-lsp"
                dockerfile_path: "Dockerfile"
                context_path: "."
                dependent_jobs:
                  - repo: "konveyor/tackle2-addon-analyzer"
                    image: "quay.io/konveyor/tackle2-addon-analyzer:latest"
                    dockerfile_path: "Dockerfile"
                    context_path: "."
                    go_mod_update:
                      - "github.com/konveyor/analyzer-lsp@${{ inputs.branch }}"
                      - "github.com/konveyor/tackle2-addon@${{ inputs.branch }}"
                      - "github.com/konveyor/tackle2-hub@${{ inputs.branch }}"
              - repo: "konveyor/analyzer-lsp" 
                image: "quay.io/konveyor/golang-dependency-provider"
                dockerfile_path: "./external-providers/golang-dependency-provider/Dockerfile"
                context_path: "."
                go_mod_update: 
                  - "github.com/konveyor/analyzer-lsp@${{ inputs.branch }}"
                dependent_jobs:
                  - repo: "konveyor/analyzer-lsp"
                    image: "quay.io/konveyor/generic-external-provider"
                    dockerfile_path: "./external-providers/generic-external-provider/Dockerfile"
                    context_path: "."
                    go_mod_update:
                      - "github.com/konveyor/analyzer-lsp@${{ inputs.branch }}"
              - repo: "konveyor/analyzer-lsp" 
                image: "quay.io/konveyor/yq-external-provider"
                dockerfile_path: "./external-providers/yq-external-provider/Dockerfile"
                context_path: "."
                go_mod_update:
                  - "github.com/konveyor/analyzer-lsp@${{ inputs.branch }}"
              - repo: "konveyor/analyzer-lsp"
                image: "quay.io/konveyor/java-external-provider"
                dockerfile_path: "./external-providers/java-external-provider/Dockerfile"
                context_path: "."
                go_mod_update:
                  - "github.com/konveyor/analyzer-lsp@${{ inputs.branch }}"
          - repo: "konveyor/static-report"
            image: "quay.io/konveyor/static-report"
            dockerfile_path: "Dockerfile"
            context_path: "."
            dependent_jobs:
              - repo: "konveyor/kantra"
                image: "quay.io/konveyor/kantra"
                dockerfile_path: "Dockerfile"
                context_path: "."
                go_mod_update:
                  - "github.com/konveyor/analyzer-lsp@${{ inputs.branch }}"
                  - "github.com/konveyor/analyzer-lsp/external-providers/java-external-provider@${{ inputs.branch }}"
                  - "github.com/konveyor/analyzer-lsp/asset-generation@${{ inputs.branch }}"
              - repo: "konveyor/tackle2-hub"
                image: "quay.io/konveyor/tackle2-hub"
                dockerfile_path: "Dockerfile"
                context_path: "."
                args: "SEED_BRANCH=${{ inputs.branch }}"
                go_mod_update:
                  - "github.com/konveyor/tackle2-seed@${{ inputs.branch }}"
    steps: 
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ matrix.config.repo }}
          ref: ${{ github.event.inputs.branch }}
      - name: Update go mod to the branch
        id: go_mod
        shell: bash
        if: matrix.config.go_mod_update != "" && matrix.config.go_mod_update[0] != null
        run: |
          for mod_update in ${{ join(fromJSON(matrix.config.go_mod_update), ' ') }}
          do
            echo "updating go mod $mod_update"
            go get -u $mod_update
          done
      - name: Get Nightly Tag
        id: get_tag
        shell: bash
        run: |
          date=$(date +'%Y.%m.%d')
          echo "tag=${{ inputs.branch }}_$date" >> $GITHUB_OUTPUT

      - name: build image
        uses: shawn-hurley/ci/build-image@main
        with:
          repo: ${{ matrix.config.repo }}
          ref: ${{ inputs.branch }}
          #base_image: ${{ matrix.base_image }}
          image_name: ${{ matrix.config.image }}
          image_tag: ${{ steps.get_tag.outputs.tag }}
          dockerfile_path: ${{ matrix.config.dockerfile_path }}
          build_context: ${{ matrix.config.context_path }}
          checked_out: true

